global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    consul_sd_configs:
    - server: localhost:8500
      services: 
        - internal-prometheus
    