all:
  hosts:
    master:
      ansible_host: 10.51.13.29
      ip: 10.51.13.29
      access_ip: 10.51.13.29
    node1:
      ansible_host: 10.51.13.30
      ip: 10.51.13.30
      access_ip: 10.51.13.30
  children:
    kube-master:
      hosts: 
        master:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        node1:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube-master:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
